<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<Platforms>x64</Platforms>

		<Version>1.0.2</Version>
		<Authors>Shadman Sakib</Authors>
		<Company>Personal</Company>
		<PackageId>LibtorrentRTWrapper</PackageId>
		<Description>Windows C++ bindings for LibTorrent</Description>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PublishUrl>https://github.com/sakib1361/LibTorrentNet</PublishUrl>
		<RepositoryUrl>https://github.com/sakib1361/LibTorrentNet</RepositoryUrl>
	</PropertyGroup>

	<!--<ItemGroup>
		<ProjectReference Include="..\LibTorrentWrapper\LibTorrentWrapper.vcxproj" PrivateAssets="All"/>
	</ItemGroup>-->
	<ItemGroup>
		<NativeLibs Include="..\vcpkg_installed\x64-windows\x64-windows\debug\bin\*.dll" Condition="'$(Configuration)' == 'Debug'" />
		<NativeLibs Include="..\vcpkg_installed\x64-windows\x64-windows\bin\*.dll" Condition="'$(Configuration)' == 'Release'" />
		<ContentWithTargetPath Include="@(NativeLibs)">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<TargetPath>%(Filename)%(Extension)</TargetPath>
		</ContentWithTargetPath>
		<None Include="..\x64\Release\*.dll" Pack="true" PackagePath="lib\net9.0-windows7.0\" Visible="false" />
		<None Include="..\vcpkg_installed\x64-windows\x64-windows\bin\*.dll" Pack="true" PackagePath="lib\net9.0-windows7.0\" Visible="false" />
	</ItemGroup>
	<!--<ItemGroup Condition="'$(Configuration)' == 'Debug'">
		<ContentWithTargetPath Include="..\vcpkg_installed\x64-windows\x64-windows\debug\bin\*.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<TargetPath>%(Filename)%(Extension)</TargetPath>
		</ContentWithTargetPath>
	</ItemGroup>
	<ItemGroup Condition="'$(Configuration)' == 'Release'">
		<ContentWithTargetPath Include="..\vcpkg_installed\x64-windows\x64-windows\bin\*.dll" Pack="true">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<TargetPath>%(Filename)%(Extension)</TargetPath>
		</ContentWithTargetPath>
	</ItemGroup>-->
	<ItemGroup>
		<None Include="..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>
	<ItemGroup>
	  <Reference Include="LibTorrentWrapper">
	    <HintPath>..\x64\Release\LibTorrentWrapper.dll</HintPath>
	  </Reference>
	</ItemGroup>
</Project>
